version: '3.9'
services:
    app:
        image: bhakundo-app
        container_name: bhakundo-app
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: bhakundo-app
            DB_USERNAME: root
            DB_PASSWORD: password
            APP_ENV: local
            APP_DEBUG: true
            APP_KEY: base64:abcdefghijklmnopqrstuvwxyz0123456789=
            LOG_CHANNEL: daily
            LOG_LEVEL: debug
        depends_on:
            - mysql
        networks:
            - app-network

    mysql:
        image: mysql:8.0
        container_name: bhakundo-mysql
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: bhakundo-app
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - '3306:3306'
        networks:
            - app-network

volumes:
    mysql_data:

networks:
    app-network:
        driver: bridge
